[package]
name = "microstrain-inertial"
authors = ["Jeff McBride <jeff@jeffmcbride.net>"]
description = "Library for communicating with Microstrain IMUs via MIP"
keywords = ["no_std", "embedded", "parser"]
categories = ["embedded", "no-std", "no-std::no-alloc"]

version = "0.0.1"
edition = "2024"

[dependencies]
critical-section = "1.2.0"
thiserror = "2.0.17"

[dev-dependencies]
clap = { version = "4.5.58", features = ["derive"] }
critical-section = { version = "1.2.0", features = ["std"] }
serialport = "4.8.1"
