[package]
name = "microstrain-inertial"
authors = ["Jeff McBride <jeff@jeffmcbride.net>"]
license = "MIT"
description = "Library for communicating with Microstrain inertial measurement units via MIP protocol"
keywords = ["no_std", "embedded", "parser", "IMU"]
categories = ["embedded", "no-std", "no-std::no-alloc"]

version = "0.0.1"
edition = "2024"
rust-version = "1.88"

[dependencies]
bbqueue = { version = "0.6.0", default-features = false, features = ["critical-section"] }
critical-section = "1.2.0"
defmt = { version = "1.0.1", optional = true }
log = "0.4.29"
serial2 = { version = "0.2.34", optional = true }
thiserror = { version = "2.0.17", default-features = false }

[dev-dependencies]
clap = { version = "4.5.58", features = ["derive"] }
critical-section = { version = "1.2.0", features = ["std"] }
env_logger = "0.11.9"
serialport = "4.8.1"
tokio = { version = "1.49.0", features = ["macros", "rt", "time"] }

[features]
default = ["serialport", "std"]
defmt = ["dep:defmt"]
std = []
serialport = [ "std", "dep:serial2" ]
